import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:portfolio/portfolioTheme.dart';

class Resume extends StatelessWidget {
  const Resume({super.key});

  @override
  Widget build(BuildContext context) {
    List<Widget> languages = [
      item("Python"),
      item("Java"),
      item("Dart"),
      item("SQL"),
      item("Javascript"),
      item("Typescript"),
      item("C++"),
    ];
    List<Widget> frameworks = [
      item("HTML5"),
      item("CSS"),
      item("Flask"),
      item("Angular"),
      item("Django"),
      item("React"),
      item("SpringBoot"),
      item("Flutter"),
      item("jQuery"),
    ];
    List<Widget> tools = [
      item("Git"),
      item("GitHub"),
      item("MS Office"),
      item("VScode"),
      item("Photoshop"),
      item("Figma"),
      item("Illustrator"),
    ];

    List<List> list = [
      [
        "Internship included numerous modules which were to be developed using Angular framework with backend processes in SpringBoot technology.",
        "Admin Panel was a major project wherein I developed the portal from scratch with login, task, and location modules integrated with backend services for dynamic response.",
        "Generated a database for storing essential information and applied CRUD operations."
      ],
      [
        "Prakarsh is a national level tech-fest organized annually at SVIT.",
        "Made significant contribution in developing the frontend for website & application of the event.",
        "Worked with colleagues to accomplish the event's graphics work, which included designing posters, banners, certificates,and more."
      ],
      [
        "Vision is an intra department college tech fest aimed at fostering healthy competition between different departments at SVIT.",
        "Lead the team which was responsible for making the Vision X website and graphics required for the event.",
        "Developed a flutter app to make viewing events simple and easy.",
      ],
      [
        "Developed dynamic and interactive android/iOS application using cross-platform framework Flutter with dart as a programming language.",
        "Worked on the application's entire front-end, involving integration of backend data to the frontend layer. Also made significant contributions to the backend.",
        "Provide an efficient way for students to view their academic details and curriculum."
      ],
      [
        "Worked closely with the project colleagues to establish a system which ensures easy interaction and management of the library.",
        "Model is designed in such a way that it can be implemented in any university at cheaper cost.",
        "Provide an efficient way for students to view and manage library related stuff."
      ],
      [
        "Characterizing each customer into a particular segment using the RFM model after preprocessing and visualizing data distribution.",
        "Using k-means and forest classifier, the result generated by RFM model was verified and predicted customer profitability over time based on time series.",
      ],
      [
        "Performed exploratory data analysis using Python for a given dataset of a retail store by plotting various data visualization graphs. ",
        "Designed various machine learning models to predict weekly sales across multiple stores and analyze the impact of external factors on the prediction.",
        "Applied different classification algorithms and performed hyper-parameter tuning for the Deep Learning models."
      ]
    ];

    return ListView(
      padding: EdgeInsets.only(top: 40),
      primary: true,
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Column(
              children: [
                Container(
                  width: MediaQuery.of(context).size.width * 0.25,
                  padding: EdgeInsets.all(22),
                  decoration: BoxDecoration(
                    color: const Color(0xff2C2C2C),
                    borderRadius: BorderRadius.circular(44),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        backgroundColor: Colors.white,
                        radius: 50,
                        child: Image.asset(
                          'assets/profile.png',
                        ),
                      ),
                      const SizedBox(height: 10),
                      Text(
                        "Suraj Shah",
                        style: PortfolioTheme.heading.copyWith(fontSize: 20),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        "Graduate Student @ CSULB",
                        style: TextStyle(
                            fontFamily: "DMsans",
                            fontSize: 20,
                            color: Theme.of(context).primaryColor),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        "Surajnandkishor.shah01@student.csulb.edu",
                        style: PortfolioTheme.subHeading,
                      ),
                      Text(
                        "www.surajshah01.me",
                        style: PortfolioTheme.subHeading,
                      ),
                      const SizedBox(height: 20),
                      Row(
                        children: [
                          ElevatedButton(
                            onPressed: () {},
                            style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.transparent,
                                elevation: 0,
                                padding:
                                    const EdgeInsets.fromLTRB(20, 16, 20, 16),
                                textStyle: const TextStyle(
                                    fontFamily: 'Gotham',
                                    fontWeight: FontWeight.w500),
                                shape: RoundedRectangleBorder(
                                    side: const BorderSide(
                                        width: 1, // thickness
                                        color: Colors.white // color
                                        ),
                                    // border radius
                                    borderRadius: BorderRadius.circular(16))),
                            child: const Text("Contact Me"),
                          ),
                          const SizedBox(width: 20),
                          Image.asset(
                            'assets/linkedin.png',
                            scale: 1.5,
                          ),
                          const SizedBox(width: 20),
                          Image.asset(
                            'assets/github.png',
                            scale: 1.5,
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 40),
                Container(
                  width: MediaQuery.of(context).size.width * 0.25,
                  padding: EdgeInsets.all(22),
                  decoration: BoxDecoration(
                    color: const Color(0xff2C2C2C),
                    borderRadius: BorderRadius.circular(44),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        "Languages",
                        style: PortfolioTheme.heading,
                      ),
                      const SizedBox(height: 10),
                      Wrap(
                        spacing: 16,
                        runSpacing: 4,
                        children: languages,
                      ),
                      const SizedBox(height: 30),
                      Text(
                        "Web/App Development",
                        style: PortfolioTheme.heading,
                      ),
                      const SizedBox(height: 10),
                      Wrap(
                        spacing: 16,
                        runSpacing: 4,
                        children: frameworks,
                      ),
                      const SizedBox(height: 30),
                      Text(
                        "Tools",
                        style: PortfolioTheme.heading,
                      ),
                      Wrap(
                        spacing: 16,
                        runSpacing: 4,
                        children: tools,
                      ),
                    ],
                  ),
                )
              ],
            ),
            const SizedBox(width: 40),
            Container(
              width: MediaQuery.of(context).size.width * 0.55,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    "Experience",
                    style: PortfolioTheme.heading.copyWith(fontSize: 24),
                  ),
                  const SizedBox(height: 20),
                  Text(
                    "Software Engineer Intern @ Cutting Edge Infotech",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "Jan 2022 - Apr 2022",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[0].length, list[0]),
                  const SizedBox(height: 20),
                  Text(
                    "Web & Graphics Head @ Prakarsh XV",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "Dec 2019 - Feb 2020",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[1].length, list[1]),
                  const SizedBox(height: 20),
                  Text(
                    "Web & Graphics Head @ Vision X",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "Sep 2020 - Oct 2020",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[2].length, list[2]),
                  const SizedBox(height: 20),
                  Text(
                    "Projects",
                    style: PortfolioTheme.heading.copyWith(fontSize: 24),
                  ),
                  const SizedBox(height: 20),
                  Text(
                    "Campus Management System | Flutter, Dart",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "6 months",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[3].length, list[3]),
                  const SizedBox(height: 20),
                  Text(
                    "Library Management System | PHP, SQL",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "2 months",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[4].length, list[4]),
                  const SizedBox(height: 20),
                  Text(
                    "RFM based Customer Segmentation | Python, AI",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "1 months",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[5].length, list[5]),
                  const SizedBox(height: 20),
                  Text(
                    "Retail Market Analysis and Growth | Python, AI",
                    style: PortfolioTheme.title,
                  ),
                  Text(
                    "1 months",
                    style: PortfolioTheme.date,
                  ),
                  listBuilder(list[6].length, list[6]),
                  const SizedBox(height: 40),
                ],
              ),
            )
          ],
        ),
      ],
    );
  }

  Widget listBuilder(int length, List list) {
    return ListView.builder(
        padding: EdgeInsets.only(top: 10),
        shrinkWrap: true,
        itemCount: length,
        itemBuilder: (BuildContext context, index) {
          return Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(width: 10),
              const Text(
                "\u2022",
                style: TextStyle(color: Colors.white),
              ),
              const SizedBox(width: 20),
              Expanded(
                child: Text(
                  list[index],
                  style: PortfolioTheme.subHeading,
                  overflow: TextOverflow.fade,
                  maxLines: 3,
                ),
              ),
            ],
          );
        });
  }

  Widget item(String text) {
    return Text(text, style: PortfolioTheme.subHeading);
  }

  Widget bullet() {
    return Container(
      height: 5.0,
      width: 5.0,
      decoration: new BoxDecoration(
        color: Colors.white70,
        shape: BoxShape.circle,
      ),
    );
  }
}
